version: "2"
services:
  test:
    container_name: "mlt"
    image: "mlt"
    environment:
      # not using /root/.kube/config because mlt will come with a blank config there
      - KUBECONFIG=/root/.gcloudkube/config
    command: "sleep inf"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/circleci/.kube:/root/.gcloudkube
